name: API CI

on:
  push:
    branches: [develop]
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yaml"
  pull_request:
    branches: [develop]
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yaml"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: ./build/build.sh

      - name: Save API image as artifact
        if: success()
        run: |
          docker save uuid_api:latest -o /tmp/uuid_api.tar
          ls -lh /tmp/uuid_api.tar

      - name: Upload API image artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: uuid-api-image
          path: /tmp/uuid_api.tar
          retention-days: 1
